import { Regions } from './regions';

export const Prefectures = {
  1: {
    id: 1,
    name: '北海道',
    short: '北海道',
    kana: 'ホッカイドウ',
    en: 'hokkaido',
    region: Regions[1],
    neighbors: [2],
  },
  2: {
    id: 2,
    name: '青森県',
    short: '青森',
    kana: 'アオモリケン',
    en: 'aomori',
    region: Regions[1],
    neighbors: [1, 3, 5],
  },
  3: {
    id: 3,
    name: '岩手県',
    short: '岩手',
    kana: 'イワテケン',
    en: 'iwate',
    region: Regions[1],
    neighbors: [2, 4, 5],
  },
  4: {
    id: 4,
    name: '宮城県',
    short: '宮城',
    kana: 'ミヤギケン',
    en: 'miyagi',
    region: Regions[1],
    neighbors: [3, 5, 6, 7],
  },
  5: {
    id: 5,
    name: '秋田県',
    short: '秋田',
    kana: 'アキタケン',
    en: 'akita',
    region: Regions[1],
    neighbors: [2, 3, 4, 6],
  },
  6: {
    id: 6,
    name: '山形県',
    short: '山形',
    kana: 'ヤマガタケン',
    en: 'yamagata',
    region: Regions[1],
    neighbors: [4, 5, 7, 15],
  },
  7: {
    id: 7,
    name: '福島県',
    short: '福島',
    kana: 'フクシマケン',
    en: 'fukushima',
    region: Regions[1],
    neighbors: [4, 6, 8, 9, 10, 15],
  },
  8: {
    id: 8,
    name: '茨城県',
    short: '茨城',
    kana: 'イバラキケン',
    en: 'ibaraki',
    region: Regions[2],
    neighbors: [7, 9, 11, 12],
  },
  9: {
    id: 9,
    name: '栃木県',
    short: '栃木',
    kana: 'トチギケン',
    en: 'tochigi',
    region: Regions[2],
    neighbors: [7, 8, 10, 11],
  },
  10: {
    id: 10,
    name: '群馬県',
    short: '群馬',
    kana: 'グンマケン',
    en: 'gunma',
    region: Regions[2],
    neighbors: [7, 9, 11, 15, 20],
  },
  11: {
    id: 11,
    name: '埼玉県',
    short: '埼玉',
    kana: 'サイタマケン',
    en: 'saitama',
    region: Regions[2],
    neighbors: [8, 9, 10, 12, 13, 19, 20],
  },
  12: {
    id: 12,
    name: '千葉県',
    short: '千葉',
    kana: 'チバケン',
    en: 'chiba',
    region: Regions[2],
    neighbors: [9, 11, 13],
  },
  13: {
    id: 13,
    name: '東京都',
    short: '東京',
    kana: 'トウキョウト',
    en: 'tokyo',
    region: Regions[2],
    neighbors: [11, 12, 14, 19],
  },
  14: {
    id: 14,
    name: '神奈川県',
    short: '神奈川',
    kana: 'カナガワケン',
    en: 'kanagawa',
    region: Regions[2],
    neighbors: [13, 19, 22],
  },
  15: {
    id: 15,
    name: '新潟県',
    short: '新潟',
    kana: 'ニイガタケン',
    en: 'niigata',
    region: Regions[3],
    neighbors: [6, 7, 10, 16, 20],
  },
  16: {
    id: 16,
    name: '富山県',
    short: '富山',
    kana: 'トヤマケン',
    en: 'toyama',
    region: Regions[3],
    neighbors: [15, 17, 20, 21],
  },
  17: {
    id: 17,
    name: '石川県',
    short: '石川',
    kana: 'イシカワケン',
    en: 'ishikawa',
    region: Regions[3],
    neighbors: [16, 18, 21],
  },
  18: {
    id: 18,
    name: '福井県',
    short: '福井',
    kana: 'フクイケン',
    en: 'fukui',
    region: Regions[3],
    neighbors: [17, 21, 25, 26],
  },
  19: {
    id: 19,
    name: '山梨県',
    short: '山梨',
    kana: 'ヤマナシケン',
    en: 'yamanashi',
    region: Regions[3],
    neighbors: [11, 13, 14, 20, 22],
  },
  20: {
    id: 20,
    name: '長野県',
    short: '長野',
    kana: 'ナガノケン',
    en: 'nagano',
    region: Regions[3],
    neighbors: [10, 11, 15, 16, 19, 21, 22, 23],
  },
  21: {
    id: 21,
    name: '岐阜県',
    short: '岐阜',
    kana: 'ギフケン',
    en: 'gifu',
    region: Regions[3],
    neighbors: [16, 17, 18, 20, 23, 24, 25],
  },
  22: {
    id: 22,
    name: '静岡県',
    short: '静岡',
    kana: 'シズオカケン',
    en: 'shizuoka',
    region: Regions[3],
    neighbors: [14, 19, 20, 23],
  },
  23: {
    id: 23,
    name: '愛知県',
    short: '愛知',
    kana: 'アイチケン',
    en: 'aichi',
    region: Regions[3],
    neighbors: [20, 21, 22, 24],
  },
  24: {
    id: 24,
    name: '三重県',
    short: '三重',
    kana: 'ミエケン',
    en: 'mie',
    region: Regions[4],
    neighbors: [21, 23, 24, 25, 26, 29, 30],
  },
  25: {
    id: 25,
    name: '滋賀県',
    short: '滋賀',
    kana: 'シガケン',
    en: 'shiga',
    region: Regions[4],
    neighbors: [18, 21, 24, 26],
  },
  26: {
    id: 26,
    name: '京都府',
    short: '京都',
    kana: 'キョウトフ',
    en: 'kyoto',
    region: Regions[4],
    neighbors: [18, 24, 25, 27, 28, 29],
  },
  27: {
    id: 27,
    name: '大阪府',
    short: '大阪',
    kana: 'オオサカフ',
    en: 'osaka',
    region: Regions[4],
    neighbors: [26, 28, 29, 30],
  },
  28: {
    id: 28,
    name: '兵庫県',
    short: '兵庫',
    kana: 'ヒョウゴケン',
    en: 'hyogo',
    region: Regions[4],
    neighbors: [26, 27, 31, 33, 36],
  },
  29: {
    id: 29,
    name: '奈良県',
    short: '奈良',
    kana: 'ナラケン',
    en: 'nara',
    region: Regions[4],
    neighbors: [24, 26, 27, 30],
  },
  30: {
    id: 30,
    name: '和歌山県',
    short: '和歌山',
    kana: 'ワカヤマケン',
    en: 'wakayama',
    region: Regions[4],
    neighbors: [24, 27, 29],
  },
  31: {
    id: 31,
    name: '鳥取県',
    short: '鳥取',
    kana: 'トットリケン',
    en: 'tottori',
    region: Regions[5],
    neighbors: [28, 32, 33, 34],
  },
  32: {
    id: 32,
    name: '島根県',
    short: '島根',
    kana: 'シマネケン',
    en: 'shimane',
    region: Regions[5],
    neighbors: [31, 34, 35],
  },
  33: {
    id: 33,
    name: '岡山県',
    short: '岡山',
    kana: 'オカヤマケン',
    en: 'okayama',
    region: Regions[5],
    neighbors: [28, 31, 34, 37],
  },
  34: {
    id: 34,
    name: '広島県',
    short: '広島',
    kana: 'ヒロシマケン',
    en: 'hiroshima',
    region: Regions[5],
    neighbors: [31, 32, 33, 35, 38],
  },
  35: {
    id: 35,
    name: '山口県',
    short: '山口',
    kana: 'ヤマグチケン',
    en: 'yamaguchi',
    region: Regions[5],
    neighbors: [32, 34, 40],
  },
  36: {
    id: 36,
    name: '徳島県',
    short: '徳島',
    kana: 'トクシマケン',
    en: 'tokushima',
    region: Regions[5],
    neighbors: [28, 37, 38, 39],
  },
  37: {
    id: 37,
    name: '香川県',
    short: '香川',
    kana: 'カガワケン',
    en: 'kagawa',
    region: Regions[5],
    neighbors: [33, 36, 38],
  },
  38: {
    id: 38,
    name: '愛媛県',
    short: '愛媛',
    kana: 'エヒメケン',
    en: 'ehime',
    region: Regions[5],
    neighbors: [34, 36, 37, 39],
  },
  39: {
    id: 39,
    name: '高知県',
    short: '高知',
    kana: 'コウチケン',
    en: 'kochi',
    region: Regions[5],
    neighbors: [36, 38],
  },
  40: {
    id: 40,
    name: '福岡県',
    short: '福岡',
    kana: 'フクオカケン',
    en: 'fukuoka',
    region: Regions[6],
    neighbors: [35, 41, 43, 44],
  },
  41: {
    id: 41,
    name: '佐賀県',
    short: '佐賀',
    kana: 'サガケン',
    en: 'saga',
    region: Regions[6],
    neighbors: [40, 42],
  },
  42: {
    id: 42,
    name: '長崎県',
    short: '長崎',
    kana: 'ナガサキケン',
    en: 'nagasaki',
    region: Regions[6],
    neighbors: [41],
  },
  43: {
    id: 43,
    name: '熊本県',
    short: '熊本',
    kana: 'クマモトケン',
    en: 'kumamoto',
    region: Regions[6],
    neighbors: [40, 44, 45, 46],
  },
  44: {
    id: 44,
    name: '大分県',
    short: '大分',
    kana: 'オオイタケン',
    en: 'oita',
    region: Regions[6],
    neighbors: [40, 43, 45],
  },
  45: {
    id: 45,
    name: '宮崎県',
    short: '宮崎',
    kana: 'ミヤザキケン',
    en: 'miyazaki',
    region: Regions[6],
    neighbors: [43, 44, 46],
  },
  46: {
    id: 46,
    name: '鹿児島県',
    short: '鹿児島',
    kana: 'カゴシマケン',
    en: 'kagoshima',
    region: Regions[6],
    neighbors: [43, 45, 47],
  },
  47: {
    id: 47,
    name: '沖縄県',
    short: '沖縄',
    kana: 'オキナワケン',
    en: 'okinawa',
    region: Regions[6],
    neighbors: [46],
  },
} as const;
